package chunks

var ChunkTypes map[string]bool = map[string]bool{
	"ABMP": true,
	"BITD": true,
	"CAS*": true,
	"CASt": true,
	"CLUT": true,
	"ediM": true,
	"Fcdr": true,
	"FCOL": true,
	"FGEI": true,
	"Fmap": true,
	"Fver": true,
	"FXmp": true,
	"GRID": true,
	"ILS":  true,
	"mmap": true,
	"VWCF": true,
	"DRCF": true,
	"KEY*": true,
	"LctX": true,
	"Lnam": true,
	"MCsL": true,
	"snd":  true,
	"Sord": true,
	"STXT": true,
	"VWFI": true,
	"VWLB": true,
	"XMED": true,
	"XTRl": true,
	"VWSC": true,
}
